version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v10:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "10.24"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v12:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v14:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "14.21"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v16:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.20"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v18:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "18.20"
      - run:
          name: update
          command: sudo apt update && sudo apt install -y libssl-dev
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v20:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "20.12"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
  test-v22:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "22.0"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Run test
          command: npm start
      - run:
          name: Verify build
          command: echo "Build and test completed successfully!"
workflows:
  build_and_test:
    jobs:
      - test-v16
      - test-v18
      - test-v20
      - test-v22